version: "3.9"  
services:
  timeCalculator:
    container_name: timeCalculator
    image: deneme1 
    build:
      context: .
      dockerfile: ./Dockerfile 
    ports:
      - "8080:8080" 
    command: bash -c "python3 /home/timeCalculator.py"