name: ci-workflow

on:
  push:
    branches: [ main ]

env:
  TIMEZONE: ${{ secrets.TIMEZONE }}
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/login-action@v1
        with:
          images: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/login-action@v1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  ci-demo:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - uses: actions/checkout@v2
  
      - name: Set up a python virtual environment
        run: | 
          python3 -m venv iaac-venv
          source iaac-venv/bin/activate
          python3 -m pip install --upgrade pip
          sudo apt-get install python3-setuptools
          pip3 install requests
          
      - name: Deploy timeCalculator
        run: |
          source iaac-venv/bin/activate
          python3 timeCalculator.py
    
      - name: Run pyATS unit-tests 
        run: |
          source iaac-venv/bin/activate
          cd ./testing
          pyats run job dev_task.py
